<?php
// Generated by ZF2's ./bin/classmap_generator.php
return array(
    'Email\Module'               => __DIR__ . '/Module.php',
    'Email\Email'                => __DIR__ . '/src/Email/Email.php',
    'Email\Service\EmailService' => __DIR__ . '/src/Email/Service/EmailService.php',
);