<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html>
	<head>
		<meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
		<meta property="og:title" content="Your Subject goes here">
		<title><?php echo $this->company; ?></title>
	</head>
	<body leftmargin="0" marginwidth="0" topmargin="0" marginheight="0" offset="0" style="-webkit-text-size-adjust: none;margin: 0;padding: 0;background-color: #FFFFFF;width: 100%; ">
		<br />
		<br />
		<center>
			<?php echo $this->content; ?>
		</center>
		<style type="text/css">
			@media only screen and (max-width: 480px) {
				#canspamBar {
					display: inline;
				}
				#canspamBar td {
					display: block;
					margin: 0 0 10px 0;
					text-align: center !important;
				}
			}
		</style>
	</body>
</html>